### ISSUE TITLE
license and no attribution

### ISSUE THREAD

**Issue by timelyportfolio** [datastorm-open/rAmCharts#1]
`rAmCharts` is wonderful, but now that it is _official_ on CRAN, I am quite surprised that there is no attribution for `AmCharts` in the DESCRIPTION, and no mention of commercial license options.   At a minimum I would have expected based on CRAN policies, something like these lines from [visNetwork](https://github.com/DataKnowledge/visNetwork/blob/master/DESCRIPTION#L6-L7) or as another example [taucharts](https://github.com/hrbrmstr/taucharts/blob/master/DESCRIPTION#L8-L10).  It seems well worth a link to the commercial license options http://www.amcharts.com/online-store/ in DESCRIPTION/[DESCRIPTION](https://github.com/DataKnowledge/rAmCharts/blob/master/DESCRIPTION#L8-L10).

I'm very sensitive to this since `htmlwidgets` depend so much on the hard work of the JavaScript developers, and I try to err on the side of over-attribution and over-disclosure.

Thanks so much for your work on `visNetwork` and `rAmCharts`.  They really are well designed.

**Comment by Djaiff** [comment]
Thanks for having noticed it !
The version has been corrected (file DESCRIPTION and directory inst/), and a new version has been submitted on CRAN.
