### ISSUE TITLE
amRadar does not take dbl ?

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#11]
Hi,

It's a bit strange to me that the amRadar does not take dbl as input for columns other than label. Is this intentional? What's the suggested data format then?

Error in amRadar(.) : All column of data except label must be numeric

**Comment by happyshows** [comment]
update:

I found out the problem seems to be the class of data frame was more than data.frame. amradar does not seems to take tbl_df well....

**Comment by TitouanRobert** [comment]
Hi,
i have update, now dbl are accepted and tbl_df are convert to data.frame inide function,

library(dplyr)

ds <- tbl_df(iris)
ds$label <- as.character(ds$Species)
ds$Species <- NULL
ds <- ds[c(1,51,101),] 
amRadar(ds)

Regards,

**Comment by happyshows** [comment]
confirmed

**Comment by happyshows** [comment]
@TitouanRobert 

Can you make sure this also applies to other amFunctions too?

For example, I can't pass a tbl_df directly to amBarplot or I'll be getting the following error.
Warning: Error in amBarplot: The column  psf  of the dataframe must be character

After I added as.data.frame, the error is gone.
