### ISSUE TITLE
amRadar legend = T/F function not working?

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#12]
Hi,

Can you double check if this switch is working or not?

In addition, is it possible to change the position and layout of legend? for example, put it on left/right side vertically. like the one implemented in visNetwork.

Thanks.

**Comment by TitouanRobert** [comment]
Hi,

I have update, legend works now. For legend position (and others arguments : subtitle, export ...) we will create a generic function for all graphs. This will avoid having redundant parameters in all functions. It's in development.

Regards

**Comment by happyshows** [comment]
confirmed
