### ISSUE TITLE
some issue with the input type for mainSize parameter

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#13]
Hi,

I was trying to make this parameter dynamic by changing it with the # of axis on radar map

```
fontSize <- max(as.integer(16 / (log(nrow(dat))+1)),8L)
amRadar(dat, mainSize = fontSize,legend = FALSE)
```

But somehow it throws an error below
Error in amRadar(dat, mainSize = fontSize) : 
  mainSize must be a numeric or double

**Comment by happyshows** [comment]
It seems to take fontSize <- 10 but not fontSize <- 10L

**Comment by TitouanRobert** [comment]
Hi,
I have update function, it works now.
Regards
