### ISSUE TITLE
Provide a detailed example of how to use amGanttChart

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#14]
It's not on the example nor Rd file. Thanks.

**Comment by TitouanRobert** [comment]
Hi,

amGantChart is not a "simple" build function, you can see build exemple on shiny application (inst/shiny). See tab named "Complex Function". This application is still in developpement, some graphs need update.

Regards,
Titouan

**Comment by jwang-lilly** [comment]
happyshows, have you managed to use amGanttChart?
