### ISSUE TITLE
[Feature Request] More flexibility in amCandlestick x-axis

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#15]
Hi,

I'm experimenting to use candlestick diagram to visualize some weekly dataset (non-stock related)
Is it possible to make the date column to a sorted vector or something like that type?

for example, the category I am using is like '2016W01, 2016W02, .....'

Thanks

**Comment by happyshows** [comment]
Also, maybe the 'open/close/low/high' can be changed to other names?

**Comment by ElenaDatak** [comment]
Hi, 

The column "category" could be a character, it works. For example : 

``` r
data("data_candleStick1")
data_test <- data_candleStick1
data_test$category <- LETTERS[1:13]
amCandlestick(data_test)
```

To try this please go to the amFunctions branch.

**Comment by happyshows** [comment]
@ElenaDatak I am not able to find the data_candleStick1 dataset, could you show where to get it?

**Comment by happyshows** [comment]
@ElenaDatak  The category part works great, can candlestick function to be more flexible to accept names other than  'open/close/low/high'?  For example, I want to change it to beginning on hand, ending on hand, low , high. I'm trying to create a visualization to tackle inventory problem.

thanks.

**Comment by ElenaDatak** [comment]
If you want to display different names in the tooltip, you can do it thanks to the 'names' argument. 

For example : 

``` r
data("data_candleStick1")
amCandlestick(data = data_candleStick1, names = c("min", "begin", "end", "max"))
```

**Comment by ElenaDatak** [comment]
You will find data_candleStick1.rda in the data directory

**Comment by happyshows** [comment]
very cool, will this feature be pulled in to the master branch soon?

**Comment by happyshows** [comment]
@ElenaDatak can you make sure all amFunctions will accept tbl_df as input data class?
