### ISSUE TITLE
[Enhancement] Allow user to define precision on final output

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#16]
Hi,

I'm experimenting candlestick chart. When user hover over the chart to see detailed number, I'd like to limit the precision to be 0 digits, instead of 2.

Can this be done as a parameter for candlestick and possibly other charts?

Thanks.

**Comment by Djaiff** [comment]
Hi,

This is a common property for any amcharts, see the running example below :

```
data("data_candleStick2")
amCandlestick(data = data_candleStick2, horiz = TRUE) %>>%
  setProperties(precision = 0) 
```

However, in this specific case, values seems not to be processed for the grey sticks. I don't know why it fails, everything's transmitted correctly to the amcharts js library.

I've tried on the chart types, and it seems to work as expected.

**Comment by happyshows** [comment]
Do I need to re-install the dev version? I am still seeing two digit precision....

**Comment by happyshows** [comment]
![image](https://cloud.githubusercontent.com/assets/3208181/12720191/15db924e-c8bf-11e5-9922-dd23e4f6572f.png)

**Comment by ElenaDatak** [comment]
Hello, 
We have fixed the problem. You can load the last version of the master branch.
