### ISSUE TITLE
Hover window frame color does not change when mouse is on a different bar candlestick already

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#17]
Hi,

Please find the attached example, I'm expecting the frame color to be green or configurable.
![untitled](https://cloud.githubusercontent.com/assets/3208181/12654714/033a3d40-c5bb-11e5-9bcf-8236445a0796.png)

**Comment by ElenaDatak** [comment]
Hi, 

This problem is now solved.
