### ISSUE TITLE
[question] purpose of pathToImages function?

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#2]
Hi,

I'm considering to utilize this package but my server that hosts application does not have access to internet. What's the purpose of pathToImages = "http://www.amcharts.com/lib/3/images/  in waterfall report example? Can such internet dependency be removed?

Thanks

**Comment by Djaiff** [comment]
Hi,

We've just removed this dependency in the current version on GitHub.
According to our tests, everything works apart from the export with htmlwidgets::saveWidget(). For this function we will have to rewrite the code, to include the images. It will be done soon.

Let me know if it does no work ! :-)
