### ISSUE TITLE
AmStockChart excel download

### ISSUE THREAD

**Issue by luxsush** [datastorm-open/rAmCharts#20]
Hi,

When I use the setExport feature to extract the data associated with an AmStockChart in an excel format or any other format, the file name is always "AmCharts".  Can I configure the settings to change the filename?

Regards,
SD

**Comment by TitouanRobert** [comment]
Hi, 

You can modify fileName option like it's :

library(rAmCharts)
library(pipeR)
data("data_radar")

exportFormat <- c("JPG", "CSV")
exportMenu <- lapply(exportFormat, function(format) {
  list(format = format, label = paste("Download as", format), title = format, fileName = format)
})

amRadar(data_radar) %>>%
setExport(enabled = TRUE,
          menu = list(list(class = "export-main", menu = exportMenu))) 

If you want more information, you can found them here.

https://github.com/amcharts/export

Regards,
Titouan

**Comment by luxsush** [comment]
This is excellent.  Can you also help me build the below related java code in R which would enable me to add a text before the chart is saved.

"afterCapture": function(menuConfig) {
      var text = new fabric.Text("This is shown on exported image only", {
        top: 50,
        left: 100,
        family: this.setup.chart.fontFamily,
        size: this.setup.chart.fontSize \* 2
      });
      this.setup.fabric.add(text);
  },

Highly appreciate your help on this.

Regards,
SD

**Comment by debsush** [comment]
+1

**Comment by happyshows** [comment]
+1

**Comment by bthieurmel** [comment]
Hi,

Use the `htmlwidgets` JS function like this : 

```
amRadar(data_radar) %>>%
  setExport(enabled = TRUE,
            afterCapture = htmlwidgets::JS('function(menuConfig) {
              var text = new fabric.Text("This is shown on exported image only", {
                top: 50,
                left: 100,
                family: this.setup.chart.fontFamily,
                size: this.setup.chart.fontSize * 2
              });
              this.setup.fabric.add(text);
            }'),
            menu = list(list(class = "export-main", menu = exportMenu))) 
```

**Comment by happyshows** [comment]
It works, maybe in future the exportMenu can be parameterized into 'simple' 'full' mode. I believe a straight link for csv and jpg/png download should be good enough for most users.

**Comment by luxsush** [comment]
This is superb stuff
