### ISSUE TITLE
[Enhancement] Convert factor column into character column by default

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#23]
Hi,

While it's doable outside of the amFunctions, it might just be easier to implement inside them.
Would amFunction be able to take both character and factor columns in x-axis?

Example error code

Error in amBarplot(x = c("Quarter"), y = nms, data = dat, labelRotation = 90,  : 
  The column  Quarter  of the dataframe must be character.

**Comment by ElenaDatak** [comment]
Hi, 
This problem is solved. Thanks for highlighted.
