### ISSUE TITLE
other chart type does not take dbl except for amRadar

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#24]
referencing
#11

Hi,

It seems when I use the complex function, the dataProvider has to be data frame class.
If I feed in a tbl_df object without the as.data.frame(), below error msg will show up.

 amSerialChart(graphs = graphs_ls, theme = 'light',categoryField = 'Week') %>%
      setDataProvider(dataProvider = dat) 

Warning: Error in <Anonymous>: unable to find an inherited method for function ‘setDataProvider’ for signature ‘"AmChart", "tbl_df", "missing"’
Stack trace (innermost first):

**Comment by bthieurmel** [comment]
Fix now updating `setDataProvider` method.

**Comment by happyshows** [comment]
@bthieurmel  I still found this error when I use the latest dev version, could you take a another look?

`R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C  
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] digest_0.6.8         rAmCharts_1.1.3      httr_1.1.0           jsonlite_0.9.16  
 [5] taucharts_0.4.4.9000 ADAP.Util_0.5.0      tidyr_0.4.1          dplyr_0.4.3.9001  
 [9] shinyBS_0.61         shinydashboard_0.5.1 shinyAce_0.2.1       DT_0.1.45  
[13] rpivotTable_0.1.5.9  shiny_0.13.1.9000   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3        pipeR_0.6.0.6      RColorBrewer_1.1-2 RJDBC_0.2-4  
 [5] tools_3.2.1        RSQLite_1.0.0      lattice_0.20-31    DBI_0.3.1  
 [9] rstudioapi_0.5     yaml_2.1.13        curl_0.9.2         rJava_0.9-6  
[13] knitr_1.12.3       htmlwidgets_0.5.2  devtools_1.6.1     grid_3.2.1  
[17] data.table_1.9.6   R6_2.0.1           magrittr_1.5       htmltools_0.3  
[21] rlist_0.4.5.1      assertthat_0.1     mime_0.3           xtable_1.7-4  
[25] httpuv_1.3.3       lazyeval_0.1.10    chron_2.3-45       zoo_1.7-11 `

**Comment by bthieurmel** [comment]
Clean & restart your session to be sure that the package is updated. 

Normally, all of this working : 

```
require(rAmCharts)
require(dplyr)
require(data.table)

data(data_gdp)

amPieChart(valueField = 'gdp', titleField = 'country', 
           dataProvider = data_gdp)

amPieChart(valueField = 'gdp', titleField = 'country', 
           dataProvider = data.table(data_gdp))

amPieChart(valueField = 'gdp', titleField = 'country', 
           dataProvider = tbl_df(data_gdp))

amPieChart(valueField = 'gdp', titleField = 'country') %>%
  setDataProvider(data_gdp)

amPieChart(valueField = 'gdp', titleField = 'country') %>%
  setDataProvider(data.table(data_gdp))

amPieChart(valueField = 'gdp', titleField = 'country') %>%
      setDataProvider(tbl_df(data_gdp))
```

**Comment by happyshows** [comment]
@bthieurmel 

In R/tools_amTests.R  you have the following code, which is causing such problem I guess
`stop(paste0("class(", arg, ") is not in c('data.frame', 'data.table', 'tbl')"))`

should be tbl_df not just tbl

In addition, I learned that instead of using not %in%, inherits(data, 'data.frame') is a cleaner solution.

**Comment by bthieurmel** [comment]
This code is just the error message, not the control. Every thing seems to work for me with current version, using `amFunctions` or not, and `data.frame`, `data.table`, `tbl_df` or `tbl_dt`.

If not, using the latest version, please send us a concrete example on which you have an error.

**Comment by happyshows** [comment]
I reinstalled the dev version, please find the below minimal example that fail:

```
library(dplyr)
library(tidyr)
library(rAmCharts)

src <- frame_data(
  ~Quarter,~Stage,~Qty,
  '01','A',0,
  '02','A',0,
  '03','A',3,
  '01','B',13,
  '02','B',200,
  '03','B',41
) %>% spread(Stage,Qty,fill = 0)

amBarplot(x='Quarter',y= c('A','B'),data = src, stack_type = 'regular') 
```

Error msg:
`Error in .testFormatData(data) : 
  class(data) is not in c('data.frame', 'data.table', 'tbl')`

Note once data frame ran through spread() function, it lost the 'tbl' in its class

**Comment by bthieurmel** [comment]
Thanks. This example work for me with `dplyr_0.4.3` and `tidyr_0.4.1`. This packages cause numerous bugs with classes and functions S4. In my case, src have class `"tbl_df"     "tbl"        "data.frame"` after `spread()` function

**Comment by happyshows** [comment]
Mine is on  tidyr_0.4.1.9000   dplyr_0.4.3.9001

That's why using inherit(dat,'data.frame') seems to be safer.

**Comment by bthieurmel** [comment]
I think (I hope...!) the problem is now resolved for both version of `dplyr`.

**Comment by happyshows** [comment]
Thanks, new release works on the code I provided.
