### ISSUE TITLE
Bug in the trend button

### ISSUE THREAD

**Issue by debsush** [datastorm-open/rAmCharts#29]
Hi,

1 bug detected - if you use drawingIconsEnabled = TRUE and double click the erase button two times, it takes you to Amcharts HomePage.

Also, would like to replicate the example "http://www.amcharts.com/tips/catching-click-events-putting-markers-stock-chart/" but not sure how.  I would like to trigger the drawing functionality on click of a random button

Thank you
Sushanta

**Comment by bthieurmel** [comment]
Hi,
Can you provide us an example for `drawingIconsEnabled = TRUE` ?

**Comment by debsush** [comment]
Actually it is not just the trend button but also the ShowAll text on the top right for zoomout

**Comment by debsush** [comment]
I think I understand the problem now.  The default creditsPosition is top right in my stockchart which overlaps with "Show All" or the Trend Line Button.  Now when I try to click "Show All", it clicks the JS chart by amCharts.com link and goes to its homepage.

Now I have run into a second problem.  The creditsPosition="top-left" is not working.   I used it on all my stockpanels

```
      stockpanels_Fund <<- lapply(1:1, function(i)
        (stockPanel(id='FD',
                    Title="Main",
                    creditsPosition="top-left",
                    precision=2,
                    showCategoryAxis= FALSE,
                    stockGraphs=stockgraphs_Fund,
                    allowTurningOff = FALSE,
                    thousandsSeparator=",",
                    recalculateToPercents="never",
                    borderAlpha = .2)%>>%
           setValueAxes(valueAxis_fund)%>>%
           setStockLegend(labelText= '[[title]]',
                          periodValueTextComparing = '[[percents.value.close]]%',
                          periodValueTextRegular = '[[value.close]]'
           )))
```

**Comment by debsush** [comment]
Need to fix the credits position at panelSettings and not at individual panels
