### ISSUE TITLE
[Question] AddListener

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#3]
Hi,

could you provide an example on assigning a value from the listened event to a session variable on shiny? The purpose is to enable cross filtering or drill down.

Thanks,

**Comment by Djaiff** [comment]
Hi,
I'm afraid of not to understand what you really want to do. Does your question deal with shiny reactivity or JavaScript listener ? Could you maybe give an illustrative example ?

**Comment by happyshows** [comment]
Hi,

for example, you have the following code that will show up an alert prompt window when band is clicked.
addListener('clickBand', 'function(event) { alert(\'clicked on band !\') }')

instead of showing an alert window, can this selected value be assigned to a session object?
See Interaction with Shiny section
http://rstudio.github.io/DT/shiny.html

I personally find such very useful because it allows me to link with other diagram/tables for drilling down.

**Comment by Djaiff** [comment]
Hi,

We can use the event properties of the listener functions and combine this with the JavaScript function "`Shiny.onInputChange`". You can refer to this for more details: https://ryouready.wordpress.com/2013/11/20/sending-data-from-client-to-server-and-back-using-shiny/.

This is a simple example in which we are able to get the value clicked. The "event" object is detailed in the official API (http://docs.amcharts.com/3/javascriptstockchart/AmSerialChart).

``` r, eval = FALSE
library(rAmCharts)
library(shiny)
library(pipeR)
shinyApp(
  ui = fluidPage(
    amChartsOutput(outputId = "chart"),
    fluidRow(
      column(width = 1, strong("Values: ")),
      column(width = 3, verbatimTextOutput("result"))
    )
  ),

  server = function(input, output) {
    output$chart <- renderAmCharts({
      # prepare data
      dp <- data.table(name = paste0('foo', 1:5),
                       income = round(rnorm(5, mean = 30000, sd = 2000)))
      # build the chart
      pipeline(
        amSerialChart(categoryField = 'name', dataProvider = dp),
        addGraph(type = 'column', valueField = "income", fillAlphas = .6),
        addListener(name = 'clickGraphItem',
                    expression = paste('function(event){',
                                       'Shiny.onInputChange(\'myValues\', event.item.values);',
                                       '}'))
      )
    })
    output$result <- renderPrint({
      input$myValues
    })
  }
)
```

I hope this will help.

**Comment by happyshows** [comment]
It works, thanks

**Comment by happyshows** [comment]
@Djaiff  Could you help look into why  below code didn't work? Thanks.
data("data_candleStick1")
amCandlestick(data = data_candleStick1, names = c("min", "begin", "end", "max")) %>% 
addListener(name = 'clickItem', expression = "function(event){ alert('ok !'); }")

**Comment by happyshows** [comment]
Nevermind, figured out the name has to be 'clickGraphItem' If you could provide more documentation on available names in ?addListener, it would be great.
