### ISSUE TITLE
[Enhancement] Facetting capability

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#32]
Maybe a workaround based on https://www.amcharts.com/demos/stacked-clustered-column-chart/?

**Comment by TitouanRobert** [comment]
Hi,

library(rAmCharts)
library(pipeR)
###Stacked Column Chart
df <- data.frame(
  year = c(2003,2004,2005,2006),
  europe = c (2.5,2.6,2.8,3.6),
  namerica = c(2.5,2.7,2.9,2.5),
  asia =  c(2.1,2.2,2.4,2.2),
  lamerica = c(0.3,0.3,0.3,0.5),
  meast = c(0.2,0.3,0.3,0.2),
  africa = c(0.1,0.1,0.1,0.3))

graphs <- list()
for(i in 2:ncol(df)){
  newstack = FALSE
  if(i == 4){
    newstack = TRUE
    }
  graphs[[i-1]] <- amGraph(balloonText="<b>[[title]]</b><br><span style='font-size:14px'>[[category]]:
                         <b>[[value]]</b></span>",
           fillAlphas = 0.8,labelText="[[value]]",lineAlpha=0.3,
           title=names(df)[i],type="column",color="#000000",valueField=names(df)[i], newStack = newstack)
}

amSerialChart(dataProvider = df, categoryField = "year", graphs = graphs) %>>%
  setLegend(horizontalGap = 10, maxColumns = 1, position = "right",
            useGraphSettings = TRUE, markerSize = 10) %>>%
  addValueAxes(stackType = "regular", axisAlpha = 0.3, gridAlpha = 0) %>>%
  setCategoryAxis(gridPosition = "start", axisAlpha = 0, gridAlpha = 0, position = "left")

Best,
Titouan

**Comment by happyshows** [comment]
Thanks, it it possible to put a 'stack name' between the bar and year label?
For example, put 'developed countries' under the 'europe+namerica' stack and 'developing countreis' as the other stack.

![image](https://cloud.githubusercontent.com/assets/3208181/13852267/499255f8-ec2f-11e5-92bc-ca3aaba58e86.png)

My use cases (implemented in taucharts)
![image](https://cloud.githubusercontent.com/assets/3208181/13852280/5f9c5420-ec2f-11e5-82a9-3cdd4844f9dc.png)

**Comment by TitouanRobert** [comment]
I think it's not possible, 

Best,
Titouan
