### ISSUE TITLE
amPlot formula option

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#34]
`amPlot(Petal.Length + Sepal.Length ~ Sepal.Width, data = iris, legend = TRUE, zoom = TRUE)`

the code in amPlot.Rd leads to a wrong legend name and value of that legend is missing.
![image](https://cloud.githubusercontent.com/assets/3208181/13849652/09ac3ed6-ec25-11e5-8cb0-6e6945fdd7ad.png)

**Comment by bthieurmel** [comment]
Fix now.
