### ISSUE TITLE
Using rAmCharts with Flex Dashboard

### ISSUE THREAD

**Issue by ThoDuyNguyen** [datastorm-open/rAmCharts#37]
I try to use rAmCharts with FlexDashboard from RStudio (http://rstudio.github.io/flexdashboard/using.html)

I played around with the layout and it seems to me that rAmCharts could not  auto re-size the chart to fit the size of the dashboard. 

Is there anything I could do to fix the issue? 

Attachment is my Rmd (I have to put it in a docx since GitHub  does not accept zip or rmd file extension)

Thank you in advance

[Rmd.docx](https://github.com/datastorm-open/rAmCharts/files/201704/Rmd.docx)

**Comment by bthieurmel** [comment]
Hi,

You just have to add `plot(width = "100%", height = "100%")` for each graphic

```
### 3D Bar plot
data("data_bar")
amBarplot(x = "country", y = "visits", data = data_bar, horiz = TRUE, depth = 15) %>>% 
plot(width = "100%", height = "100%")

```
