### ISSUE TITLE
[Question] How to override a variable created by a mouseclick event

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#38]
I'm using a mouse click listener like below
addListener(name = 'clickGraphItem', expression = paste0('function(event){',
'Shiny.onInputChange(\'clickedVal\', event.item.category)',
'}'))

However, there are cases that I need to reset input$clickedVal to '' or NULL. Shiny won't allow me to modify the input value directly. Is there anything can be done to reset the listener?

detailed case
listener is based on chart 1.
clicked value is one of the inputs for chart 2, act as a filter.
if the dataprovider chart 1 is updated, the listener should be reset to NULL, which disables chart 2, as previously clicked value is no longer valid.

Thanks.

**Comment by bthieurmel** [comment]
Hi,

Perhaps it's better to ask this question to `shiny` / `htmlwidgets` team

**Comment by happyshows** [comment]
thanks, will post a solution when I hear back from them.

**Comment by jcheng5** [comment]
I would reset the clickedVal whenever the chart 1 is rendered. You can do this from R by using the `onRender` function from `htmlwidgets`, like this:

``` r
renderAmCharts({
  amHist(...) %>% ... %>%
    htmlwidgets::onRender("function(el, x) { Shiny.onInputChange('clickedVal', null); }")
})
```

This causes htmlwidgets to call that JS function immediately after rendering the chart.

**Comment by bthieurmel** [comment]
Thanks @jcheng5. Good to know.
