### ISSUE TITLE
Asynchronous Loading of Data 

### ISSUE THREAD

**Issue by debsush** [datastorm-open/rAmCharts#39]
Hi,

Native Amcharts allow asynchronous loading of data using the dataloader pluggin (async=TRUE).  Since rAmCharts does not use the data loader pluggin, how can we build this effect in our shinyapp?

This will be a great boon to apps using a lot of data as the user will not have to wait until the entire data gets loaded

Thank you as always for all your help so far.

SD

**Comment by bthieurmel** [comment]
You can use `dataLoader` with the R package. The library is included also in the package. Normally, if you define a `dataLoader`, we load the library.

For stock, perhaps you have to use the current dev version (just have change some controls).

Let me now if it's ok.

**Comment by debsush** [comment]
An example would be most appreciated.  AmCharts.com states the data needs to be in json format.  Is it true even when we use the R package or a data frame in R

**Comment by bthieurmel** [comment]
You have to check the `dataLoader` documentation. With `dataLoader`, you pass your data with an external file, JSON or CSV.

https://www.amcharts.com/tutorials/using-data-loader-plugin/
http://www.g20ewg.org/ammap/plugins/dataloader/examples/serial_csv.html

**Comment by debsush** [comment]
Not totally clear on how I would use my data in R data frame work with it.  However, closing the issue for now until we are in a stage to see this getting implemented with data in a R data frame.  Thank you as always
