### ISSUE TITLE
Responsive = TRUE 

### ISSUE THREAD

**Issue by debsush** [datastorm-open/rAmCharts#44]
I would like to make my amCharts responsive to smaller screens.  

Example: http://codepen.io/amcharts/pen/QwgEKQ/

When I use the R equivalent of it "setResponsive(enabled=TRUE)", it throws an error

Error in <Anonymous>: unable to find an inherited method for function ‘setResponsive’ for signature ‘"AmStockChart", "logical"’

Wonder where did I go wrong

**Comment by Djaiff** [comment]
Hi,
The method `setResponsive` is only defined for the the class "AmChart", I will change this.

**Comment by debsush** [comment]
Since I am using an older version of rAmcharts, could you tell me the files that I need to change and the code I need to include in those files to make setResponsive method available for AmStock.

I am currently not interested in using the latest dev version in my project.  Thank you
