### ISSUE TITLE
Complex function available for boxPlot chart?

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#49]
Hi,

I'm wondering if there are more options to adjust boxplot like the other chart types.
Thanks.

**Comment by happyshows** [comment]
also, is there any complex function available for amBoxplot?

**Comment by bthieurmel** [comment]
Boxplot is just a "complex" serial. You can look at `
rAmCharts:::.plotAmBoxplot` in `chart_amBoxplot.R`

**Comment by happyshows** [comment]
for example, can I overlay a line chart over the boxplot (to show the current version of dataset), if so, how can I do that?

**Comment by bthieurmel** [comment]
You can for example use `amLines` with good number of values : 

```
amBoxplot(count ~ spray, data = InsectSprays) %>>%
  amLines(x = c(15, 16, 5, 6, 5, 20), col = "blue", type = "smoothedLine")
```

**Comment by happyshows** [comment]
So instead of your suggested approach, is it possible to overlay more customized chart (from two datasources, but with overlapping x-axis) on top of amboxplot?

something like
amBoxplot(dat)  %>%
        amPlot(x = current$Quarter, y = current$Qty,type = 'sl')
tested, didn't work.

Is amSerialChart + addgraph a possibility here?

**Comment by Djaiff** [comment]
Hi,
I'm afraid you can't do such things. Those functions haven't been developed with an existing chart as (first) argument, except 'amLines'.
However it's a good idea for the next versions !

Sorry
