### ISSUE TITLE
Add series to an rAmCharts using a loop

### ISSUE THREAD

**Issue by debsush** [datastorm-open/rAmCharts#5]
Hi:

I would like to dynamically add the numbers of series to an rAmchart based on user input.  How can I achieve the same.
Data Table a has n number of columns and I would like each column to represent a line series
Working example below is not working:
          "fdyG1"= pipeR::pipeline(
            amSerialChart(addClassNames = TRUE, autoMargins = FALSE,
                          marginLeft = 30, marginRight = 8,
                          marginTop = 10, marginBottom = 26, startDuration = 1,
                          categoryField = 'PERIOD', startDuration = 0),
            addGraph(bullet = 'round', lineThickness = 3,
                     bulletSize = 7, bulletBorderAlpha = 1, bulletColor = '#FFFFFF',
                     useLineColorForBulletBorder = TRUE, bulletBorderThickness = 3, 
                     fillAlphas = 0, lineAlpha = 1, title = colnames(a)[2], valueField = colnames(a)[2],
                     balloonText = balloonText),
            setDataProvider(dataProvider = a)
          )

```
      for (ctr in 3:NROW(a)){
        "fdyG1"= pipeR::pipeline(fdyG1,addGraph(bullet = 'round', lineThickness = 3,
                                                bulletSize = 7, bulletBorderAlpha = 1, bulletColor = '#FFFFFF',
                                                useLineColorForBulletBorder = TRUE, bulletBorderThickness = 3, 
                                                fillAlphas = 0, lineAlpha = 1, title = colnames(a)[ctr], valueField = colnames(a)[ctr],
                                                balloonText = balloonText),
                                 setDataProvider(dataProvider = a)
                                )
      }
```

**Comment by Djaiff** [comment]
Hi,

The " valueField" property only accepts a '`character`' vector of length 1.
In your example, you can intialize a list of graphs and give it to your Amcharts object.

A simple solution would be as follow:

``` r
library(rAmCharts)
library(shiny)
library(pipeR)

shinyApp(

  ui = fluidPage(
    sliderInput(inputId = "ctr", min = 1, max = 4, value = 2, label = "Nb. series:"),
    amChartsOutput(outputId = "charts")
  ),

  server = function(input, output){

    output$charts <- renderAmCharts({
      iris <- get("iris", "package:datasets")

      # create your graphs, each of them corresponds to one column of your dataProvider
      graphs_ls <- lapply(1:input$ctr, function(i)
        graph(bullet = 'round', lineThickness = 3, bulletSize = 7,
              bulletBorderAlpha = 1, bulletColor = '#FFFFFF',
              useLineColorForBulletBorder = TRUE, bulletBorderThickness = 3, 
              fillAlphas = 0, valueField = colnames(iris)[i],
              lineAlpha = 1, title = colnames(iris)[i])
      )

      amSerialChart(graphs = graphs_ls) %>>%
        setDataProvider(dataProvider = iris)
    })
  }
)
```

I hope it will help.
Feel free to contact if you have other questions.

Best.

**Comment by debsush** [comment]
This works like a charm.  Many thanks!!!
