### ISSUE TITLE
Charts did not perfectly fit  in flexdashboard

### ISSUE THREAD

**Issue by ThoDuyNguyen** [datastorm-open/rAmCharts#50]
http://rpubs.com/thonguyenduy/181447

I test with a 23' LCD with the resolution of 1920 x 1080, Google Chrome and I must view the page in full screen mode to see the charts properly. 

Source code was included in the page. 

Please help investigating. 

Kind regards.

**Comment by bthieurmel** [comment]
Did you try this #37 (your previous issue...!) ?

**Comment by ThoDuyNguyen** [comment]
My bad, I forgot the case I opened sometimes ago (have just read it yet). 

Thank you for your reply.
