### ISSUE TITLE
Limit the max value in Radar chart?

### ISSUE THREAD

**Issue by happyshows** [datastorm-open/rAmCharts#54]
Hi,

I'm building a radar chart to show percentage value, is there a way to limit the lower and upper value to a range so that I can ensure the consistent metrics for it. Thanks.

**Comment by TitouanRobert** [comment]
Hi,

You can update new version from git and try : 
data("data_radar")
amRadar(data_radar, xlim = c(0, 8))

Best,

**Comment by happyshows** [comment]
great, thanks.
