### ISSUE TITLE
4 arguments passed to .Internal(nchar) 

### ISSUE THREAD

**Issue by jwang-lilly** [datastorm-open/rAmCharts#55]
Dear rAmCharts developer:
(this issue is also submitted to https://github.com/DataKnowledge/rAmCharts/issues/1
While running the demo example from rAmCharts shiny, I encountered this error:
4 arguments passed to .Internal(nchar) which requires 3

According to google, this may have something to do with the version of R I have.

I just want to confirm with you. Is there any solution to avoid this error while using R 3.2.0?

Thanks,

-Jian Wang

Shiny code

```
library(shiny)
library(rAmCharts)

ui = fluidPage(amChartsOutput(outputId = "amchart"))

server = function(input, output) {
output$amchart <- renderAmCharts({
# minimal example
iris <- get(x = "iris", pos = "package:datasets")

amBoxplot(iris[, -5])
})
}

shinyApp(ui = ui, server = server)
```

sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)
locale:
[1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_PAPER=en_US.UTF-8

[8] LC_NAME=C LC_ADDRESS=C LC_TELEPHONE=C LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] shiny_0.13.2 rAmCharts_2.0.3

loaded via a namespace (and not attached):
[1] Rcpp_0.12.2 digest_0.6.9 mime_0.5 chron_2.3-47 R6_2.1.2 xtable_1.8-2 jsonlite_0.9.19 rlist_0.4.6.1 data.table_1.9.6 tools_3.2.0

[11] htmlwidgets_0.6 httpuv_1.3.3 yaml_2.1.13 rsconnect_0.4.1.11 htmltools_0.3.5 pipeR_0.6.1.3

**Comment by bthieurmel** [comment]
Hi,

As you says and you read, there is a little bug with `R 3.2.0` or older. `nchar` function seems to be modified in `3.2.1`, and so we observe bad interaction with a lot of packages....

The best way to solve that is to update R if you can....

**Comment by jwang-lilly** [comment]
Thank you!

**Comment by jwang-lilly** [comment]
Hi,

Thanks much for the advice.

May I take this opportunity to ask a related question.
At rAmCharts webpage (https://github.com/datastorm-open/rAmCharts), you mentioned gantt chart is one of the chart types.

However, I couldn’t find any example for using amGannt().  Could you share with an example of using amGannt()?  Thanks much.

-Jian

**Comment by jwang-lilly** [comment]
Thanks much for update amGannt.
