### ISSUE TITLE
example for amGanttChart

### ISSUE THREAD

**Issue by jwang-lilly** [datastorm-open/rAmCharts#57]
Hi, Could you please provide an example for amGanttChart?  Someone filed an issue for this question and was directed to complex function inst/shiny.  Among the shiny examples, amGanttChart is not included.  Please advise!
https://github.com/datastorm-open/rAmCharts/issues/14

**Comment by TitouanRobert** [comment]
Hi,

We develop a new function for gantt, you can see code in folder rAmCharts\dev\amFunctions. This function is actualy in developpement, make a copy if you use it. No-regression is not provided as long as this function is in folder dev.

Regards,
Titouan

**Comment by jwang-lilly** [comment]
This is fantastic!  Thanks much.
Just a quick question, when I call the function like the following,
amGantt(data_gantt, zoom=TRUE, legend=TRUE, scrollbar=TRUE)
The legend and scrollbar do not show up.
When I modified amGantt with setChartScrollbar(), scrollbar only shows for the y axis.  How can I have scrollbar for the x axis – time axis

-Jian

**Comment by jwang-lilly** [comment]
Titouan:  Could you please advise on enabling scrolling on x axis?  Thanks,  -Jian

**Comment by TitouanRobert** [comment]
Hi,
new version of amGantt and amOptions is commit :
amGantt(data_gantt)
data_gantt$legend <- c("category 1", "category 2", "category 1", "category 2", "category 1")
amGantt(data_gantt, valuescrollbar = TRUE)
amGantt(data_gantt, valuescrollbar = TRUE, valuescrollbarHeight = 50)

Regards,
Titouan

**Comment by jwang-lilly** [comment]
> library(rAmCharts)
> ?amGantt()
> Error in .helpForCall(topicExpr, parent.frame()) : 
>   no methods for ‘amGantt’ and no documentation for it as a function

sessionInfo()
[1] rAmCharts_2.1.0  

Have you exported amGantt()?

**Comment by jwang-lilly** [comment]
Thanks much Titouan.  I will give it a try.  Could you please also take a look at issue 59.  -Jian

**Comment by jwang-lilly** [comment]
Titouan:  Could you export the function?  Thanks,  -Jian

**Comment by TitouanRobert** [comment]
This function is actualy in developpement, we can't export. We will add others parameters and make test.

Regards,
Titouan

**Comment by jwang-lilly** [comment]
Thanks much. -Jian
