### ISSUE TITLE
setExport not available for amStockChart

### ISSUE THREAD

**Issue by debsush** [datastorm-open/rAmCharts#6]
Hi Jeff,

Currently, it seems that setExport feature is not available for amStockCharts.  How can I get those features to work such as annotate and save as in amStockCharts.  I was trying to play around with the below example but could not make it work.

http://codepen.io/amcharts/embed/54438738eb344e96a063ee2d4821ed7b?height=598

Request you to kindly help me with this

Regards,
Sushanta

**Comment by Djaiff** [comment]
Hi,

I've fixed a problem to allow the method `setExport` for an AmStockChart.
It is now available in the latest GitHub version:

``` r
devtools::install_github("dataKnowledge/rAmCharts")
```

Let me know if it does not work for you.

Regards,
Jeff

**Comment by debsush** [comment]
Thank you once again.
