### ISSUE TITLE
How to display percentage in amFunnel chart?

### ISSUE THREAD

**Issue by ThoDuyNguyen** [datastorm-open/rAmCharts#60]
Is there any proper method to display the percentage along side with the numeric value? 

My current approach is to calculate the percentage and append them to description column.

**Comment by TitouanRobert** [comment]
Hi,

You can use amFunnelChart function : 

data('data_funnel')
##Plot
g1 <- amFunnelChart(dataProvider = data_funnel, startDuration = 0,
              labelPosition = 'left', marginLeft = 200, marginRight = 100,
              titleField = 'description', valueField = 'value',
              balloonText = "<b>[[title]]</b> <br>[[value]] : [[percents]] %",
              labelText = "[[title]]: [[value]] <br>[[percents]] %")
g1

You can also modify object render by amFunnel : 

data('data_funnel')
g2 <-amFunnel(data_funnel)
g2@otherProperties$balloonText <- "<b>[[title]]</b> <br>[[value]] : [[percents]] %"
g2@otherProperties$labelText <- "[[title]]: [[value]] <br>[[percents]] %"
g2

Regards, 
Titouan

**Comment by ThoDuyNguyen** [comment]
That would be a nice solution. 

Thank you for the help.
