### ISSUE TITLE
stockChart calculated value format

### ISSUE THREAD

**Issue by jwang-lilly** [datastorm-open/rAmCharts#63]
Hi,  Could someone please advise how the calculated values displayed in legend or balloon text can be rounded to certain decimal places.  

Thanks much.

**Comment by bthieurmel** [comment]
This is one simple way using ``precision``.

````
data(data_gbar)

am <- amBarplot(x = "year", y = c("income", "expenses"), 
                data = data_gbar, zoom = TRUE,
                legend = TRUE, export = TRUE)

am@otherProperties$precision <- 0
am

am@otherProperties$precision <- 2
am
````

For other way, please refer to API.
