### ISSUE TITLE
mainColor when there is only row in input data.frame

### ISSUE THREAD

**Issue by ThoDuyNguyen** [datastorm-open/rAmCharts#64]
Is it possible to set the color in this case? 

``` r
test <-
  structure(
    list(label = "0.9", value = 20804L),
    class = "data.frame",
    row.names = c(NA,
    -1L),
    .Names = c("label", "value")
  )
```

These 2 snippet should produce same pie with different color (in my opinion)

Snippet 1: 

``` r
amPie(test, legend = TRUE, show_values = FALSE) %>%
  amOptions(mainColor = "#00ff00")
```

Snippet 2: 

``` r
amPie(test, legend = TRUE, show_values = FALSE) %>%
  amOptions(mainColor = "#d80036")
```

**Comment by TitouanRobert** [comment]
Hi, 
You can use :
test$color <- "#d80036"

amPie(test, legend = TRUE, show_values = FALSE)

mainColor should be use for title color :

amPie(test, legend = TRUE, show_values = FALSE) %>%
     amOptions(mainColor = "#00ff00", main = "My title")

Regards,
