### ISSUE TITLE
RMarkdown

### ISSUE THREAD

**Issue by wilcar** [datastorm-open/rAmCharts#65]
I am using RamCharts inside an RMarkdown document with html rendering issue. The text under the chart is not correctly rendering. The RamCharts output adds a markup before my text 

![ramcharts1](https://cloud.githubusercontent.com/assets/18226229/20702238/499bf574-b617-11e6-9ad1-1c10e10266cf.jpg)

![ramcharts2](https://cloud.githubusercontent.com/assets/18226229/20702290/7b87fe8e-b617-11e6-91f8-32c08003ea0f.jpg)

**Comment by ElenaDatak** [comment]
Hello, 

You have to add a supplementary new line.

**Comment by ElenaDatak** [comment]
For example : 
![code1](https://cloud.githubusercontent.com/assets/12731859/20704803/eb7e5ff4-b620-11e6-8f30-7ebfb04aa0ca.PNG)


we obtain the same problem : 
![test am1](https://cloud.githubusercontent.com/assets/12731859/20704559/0ca04ab8-b620-11e6-827e-9564e9d3d590.PNG)

But with : 
![code2](https://cloud.githubusercontent.com/assets/12731859/20704811/f350b75e-b620-11e6-973f-67f3387bf0f7.PNG)


We obtain : 
![test am2](https://cloud.githubusercontent.com/assets/12731859/20704646/5b804066-b620-11e6-8d5c-57647288dcd7.PNG)

In Rmd you have to  have 1 blank line to pass to the next line.

**Comment by wilcar** [comment]
Hello, thank you for your answer. 
Sorry, but it doesnt work for me...
![ramcharts1](https://cloud.githubusercontent.com/assets/18226229/20706207/6693f690-b626-11e6-9ae5-fe5fcb908b1e.jpg)


I obtain:

![ramcharts2](https://cloud.githubusercontent.com/assets/18226229/20706228/88b5576e-b626-11e6-86b0-653095057fb0.jpg)

**Comment by ElenaDatak** [comment]
Sorry I can't reproduce your error. My sessionInfo() : 

R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rAmCharts_2.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.4      digest_0.6.9     rprojroot_1.1    chron_2.3-47     jsonlite_0.9.19  backports_1.0.4 
 [7] magrittr_1.5     evaluate_0.10    stringi_0.5-5    data.table_1.9.6 rmarkdown_1.2    tools_3.2.3     
[13] stringr_1.0.0    htmlwidgets_0.8  rsconnect_0.4.3  yaml_2.1.13      htmltools_0.3.5  knitr_1.15.1    
[19] pipeR_0.6.0.6
