### ISSUE TITLE
Retain chart settings when changing chart parameters from UI

### ISSUE THREAD

**Issue by debsush** [datastorm-open/rAmCharts#7]
I have an amStockChart containing 3 time series.  During initialization, only the first time series is visible.  Now, using the DataSelector list box in the UI, i selected the remaining two series for comparison.  Now I used a checkboxinput in the UI to change the scale from normal to logarithmic.  The chart refreshes and 2/3 time series get deselected.  How can I retain the initial settings in the chart prior to such events invoked by a user in the UI.  I am assuming I should use validateNow() method but  not sure how and where to invoke it in my shiny code.  A working example would be much appreciated

Thank you

**Comment by Djaiff** [comment]
Hi,

I understand your problem, but I do not think there is a simple way to solve it. We have to find a way so that the JavaScript Library become reactive to Shiny input without refreshing the entire chart. I work on it.

**Comment by debsush** [comment]
Thanks for the update.  No worries, I will wait for the solution.  In the meantime, I will open a couple more issues to have my other queries addressed

**Comment by debsush** [comment]
Hi,

Was wondering if there has been any update with respect to the query.  Please let me know if I should reach out to the shiny team to get some cues

Regards

**Comment by Djaiff** [comment]
Hi,
I am sorry, I did not have time these last days. In my view, the problem can be solved with the amcharts library. It probably exists a method (in JS) to update the chart without resetting the series displayed. I think this has to be done outside the reactive expression with some specific methods (by implementing a JS function, a button listener, to change the scale property and call 'validateNow()').

I will have time this week to work on it. Could you give me a simple exemple which I can use as a basis ?

Regards

**Comment by debsush** [comment]
Hi,

Sincere apologies for the delay in response.  I was out of town for the holidays and returned today.  I will submit a simple example by today EOD without fail.

Regards

**Comment by debsush** [comment]
Hi,

In the CRAN manual - https://cran.r-project.org/web/packages/rAmCharts/rAmCharts.pdf, when we run the shiny example, there is an example of a AmStockChart.  If we select the second, third and fourth data set from the setDataSetSelector box, we see 4 line charts.  Now change the theme using the drop-down menu to "dark" and you find that the second, third and fourth data series previously selected now get deselected.  
What should happen - We would like the chart to retain the previous settings which means that the 4 series should continue to remain selected and theme should change to "dark".  Is it possible

Regards,

**Comment by debsush** [comment]
Any update on this.  Thank you

**Comment by Djaiff** [comment]
Hi,
I am sorry but I didn't find any solution for the moment. I am currently focused on fixing existing bugs for a new version on CRAN. This is on my 'TODO' list, I'll keep you informed !

**Comment by debsush** [comment]
Thank you.  Looking forward to the next version on CRAN

**Comment by debsush** [comment]
Any progress on this

**Comment by bthieurmel** [comment]
Related to https://docs.amcharts.com/3/javascriptstockchart?search=theme : 

"There is no way to change theme of already created chart, you have to create chart's instance once more if you want to change theme"

For others interactions, you can & have to use amcharts methods & events
