### ISSUE TITLE
Number formatting for amAngularGauge()

### ISSUE THREAD

**Issue by ghost** [datastorm-open/rAmCharts#96]
```
library(rAmCharts)
amAngularGauge(10, text = "%")
```

Is there any way to format the **10%** at the bottom like reducing the distance between `'10' and '%'`, styling `'%' `etc? Any pointer will be highly appreciated.

Thanks,

**Comment by bthieurmel** [comment]
Hi,

Of course. You just have to get ``amAngularGauge`` output and then you can add all ``amCharts`` parameters you want using ``list`` like this : 

````
library(rAmCharts)
a <- amAngularGauge(10, text = "%")

api()
# see http://docs.amcharts.com/3/javascriptstockchart/GaugeAxis

a@axes[[1]]$bottomText <- "10%"
a@axes[[1]]$bottomTextColor <- "red"

a
````
